package com.blackbeard.common.mapper.kline;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blackbeard.common.pojo.kline.KlineRecord15;
import com.blackbeard.common.pojo.kline.KlineRecord15Example;


public interface KlineRecord15Mapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int countByExample(KlineRecord15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int deleteByExample(KlineRecord15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int insert(KlineRecord15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int insertSelective(KlineRecord15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	List<KlineRecord15> selectByExample(KlineRecord15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	KlineRecord15 selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int updateByExampleSelective(@Param("record") KlineRecord15 record,
			@Param("example") KlineRecord15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int updateByExample(@Param("record") KlineRecord15 record,
			@Param("example") KlineRecord15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int updateByPrimaryKeySelective(KlineRecord15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_k_line_record_15
	 *
	 * @mbggenerated Thu Jun 16 15:08:50 CST 2016
	 */
	int updateByPrimaryKey(KlineRecord15 record);
}