package com.blackbeard.common.mapper.kline;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blackbeard.common.pojo.kline.KlineRecord5;
import com.blackbeard.common.pojo.kline.KlineRecord5Example;


public interface KlineRecord5Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int countByExample(KlineRecord5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int deleteByExample(KlineRecord5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int insert(KlineRecord5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int insertSelective(KlineRecord5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    List<KlineRecord5> selectByExample(KlineRecord5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    KlineRecord5 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") KlineRecord5 record, @Param("example") KlineRecord5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int updateByExample(@Param("record") KlineRecord5 record, @Param("example") KlineRecord5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int updateByPrimaryKeySelective(KlineRecord5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_k_line_record_5
     *
     * @mbggenerated Thu Jun 16 15:04:24 CST 2016
     */
    int updateByPrimaryKey(KlineRecord5 record);
}