package com.blackbeard.common.pojo.kline;

import java.util.Date;

public class KlineRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.id
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.currency
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.open_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.close_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.high_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String highPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.low_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.decimals
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private String decimals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.time_stamp
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private Long timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.create_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.last_update_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_k_line_record.stat
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.id
     *
     * @return the value of t_k_line_record.id
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.id
     *
     * @param id the value for t_k_line_record.id
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.currency
     *
     * @return the value of t_k_line_record.currency
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.currency
     *
     * @param currency the value for t_k_line_record.currency
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.open_price
     *
     * @return the value of t_k_line_record.open_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.open_price
     *
     * @param openPrice the value for t_k_line_record.open_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setOpenPrice(String openPrice) {
        this.openPrice = openPrice == null ? null : openPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.close_price
     *
     * @return the value of t_k_line_record.close_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.close_price
     *
     * @param closePrice the value for t_k_line_record.close_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setClosePrice(String closePrice) {
        this.closePrice = closePrice == null ? null : closePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.high_price
     *
     * @return the value of t_k_line_record.high_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.high_price
     *
     * @param highPrice the value for t_k_line_record.high_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setHighPrice(String highPrice) {
        this.highPrice = highPrice == null ? null : highPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.low_price
     *
     * @return the value of t_k_line_record.low_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.low_price
     *
     * @param lowPrice the value for t_k_line_record.low_price
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setLowPrice(String lowPrice) {
        this.lowPrice = lowPrice == null ? null : lowPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.decimals
     *
     * @return the value of t_k_line_record.decimals
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public String getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.decimals
     *
     * @param decimals the value for t_k_line_record.decimals
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setDecimals(String decimals) {
        this.decimals = decimals == null ? null : decimals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.time_stamp
     *
     * @return the value of t_k_line_record.time_stamp
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.time_stamp
     *
     * @param timeStamp the value for t_k_line_record.time_stamp
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.create_time
     *
     * @return the value of t_k_line_record.create_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.create_time
     *
     * @param createTime the value for t_k_line_record.create_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.last_update_time
     *
     * @return the value of t_k_line_record.last_update_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.last_update_time
     *
     * @param lastUpdateTime the value for t_k_line_record.last_update_time
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_k_line_record.stat
     *
     * @return the value of t_k_line_record.stat
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_k_line_record.stat
     *
     * @param stat the value for t_k_line_record.stat
     *
     * @mbggenerated Sun Jun 12 15:21:36 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}