package com.blackbeard.common.pojo.web;

import java.util.Date;

public class AccountConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.id
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.account_percent
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private Float accountPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.level
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.create_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.last_update_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_config.stat
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.id
     *
     * @return the value of t_account_config.id
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.id
     *
     * @param id the value for t_account_config.id
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.account_percent
     *
     * @return the value of t_account_config.account_percent
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public Float getAccountPercent() {
        return accountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.account_percent
     *
     * @param accountPercent the value for t_account_config.account_percent
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setAccountPercent(Float accountPercent) {
        this.accountPercent = accountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.level
     *
     * @return the value of t_account_config.level
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.level
     *
     * @param level the value for t_account_config.level
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.create_time
     *
     * @return the value of t_account_config.create_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.create_time
     *
     * @param createTime the value for t_account_config.create_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.last_update_time
     *
     * @return the value of t_account_config.last_update_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.last_update_time
     *
     * @param lastUpdateTime the value for t_account_config.last_update_time
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_config.stat
     *
     * @return the value of t_account_config.stat
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_config.stat
     *
     * @param stat the value for t_account_config.stat
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}