package com.blackbeard.common.pojo.web;

import java.util.Date;

public class CurrencyConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.id
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.currency
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.is_enable
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private Integer isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.currency_rates
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private String currencyRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.create_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.last_update_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency_config.stat
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.id
     *
     * @return the value of t_currency_config.id
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.id
     *
     * @param id the value for t_currency_config.id
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.currency
     *
     * @return the value of t_currency_config.currency
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.currency
     *
     * @param currency the value for t_currency_config.currency
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.is_enable
     *
     * @return the value of t_currency_config.is_enable
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.is_enable
     *
     * @param isEnable the value for t_currency_config.is_enable
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.currency_rates
     *
     * @return the value of t_currency_config.currency_rates
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public String getCurrencyRates() {
        return currencyRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.currency_rates
     *
     * @param currencyRates the value for t_currency_config.currency_rates
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setCurrencyRates(String currencyRates) {
        this.currencyRates = currencyRates == null ? null : currencyRates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.create_time
     *
     * @return the value of t_currency_config.create_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.create_time
     *
     * @param createTime the value for t_currency_config.create_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.last_update_time
     *
     * @return the value of t_currency_config.last_update_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.last_update_time
     *
     * @param lastUpdateTime the value for t_currency_config.last_update_time
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency_config.stat
     *
     * @return the value of t_currency_config.stat
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency_config.stat
     *
     * @param stat the value for t_currency_config.stat
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}