package com.blackbeard.common.pojo.web;

import java.util.Date;

public class Mt4Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.id
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.server_ip
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.server_port
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private Integer serverPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.userlever
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private Integer userlever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.lg_manage
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private String lgManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.lg_pword
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private String lgPword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.mid
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private String mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.create_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mt4_config.stat
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.id
     *
     * @return the value of t_mt4_config.id
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.id
     *
     * @param id the value for t_mt4_config.id
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.server_ip
     *
     * @return the value of t_mt4_config.server_ip
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.server_ip
     *
     * @param serverIp the value for t_mt4_config.server_ip
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.server_port
     *
     * @return the value of t_mt4_config.server_port
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public Integer getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.server_port
     *
     * @param serverPort the value for t_mt4_config.server_port
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.userlever
     *
     * @return the value of t_mt4_config.userlever
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public Integer getUserlever() {
        return userlever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.userlever
     *
     * @param userlever the value for t_mt4_config.userlever
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setUserlever(Integer userlever) {
        this.userlever = userlever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.lg_manage
     *
     * @return the value of t_mt4_config.lg_manage
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public String getLgManage() {
        return lgManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.lg_manage
     *
     * @param lgManage the value for t_mt4_config.lg_manage
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setLgManage(String lgManage) {
        this.lgManage = lgManage == null ? null : lgManage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.lg_pword
     *
     * @return the value of t_mt4_config.lg_pword
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public String getLgPword() {
        return lgPword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.lg_pword
     *
     * @param lgPword the value for t_mt4_config.lg_pword
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setLgPword(String lgPword) {
        this.lgPword = lgPword == null ? null : lgPword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.mid
     *
     * @return the value of t_mt4_config.mid
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.mid
     *
     * @param mid the value for t_mt4_config.mid
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.create_time
     *
     * @return the value of t_mt4_config.create_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.create_time
     *
     * @param createTime the value for t_mt4_config.create_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.last_update_time
     *
     * @return the value of t_mt4_config.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.last_update_time
     *
     * @param lastUpdateTime the value for t_mt4_config.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mt4_config.stat
     *
     * @return the value of t_mt4_config.stat
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mt4_config.stat
     *
     * @param stat the value for t_mt4_config.stat
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}