package com.blackbeard.common.pojo.web;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_password
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.mt4_id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String mt4Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.mt4_user_group
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String mt4UserGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_state
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_mail
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.blance
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Long blance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.certificate_no
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.certificate_url
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String certificateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_telphone
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private String userTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.stat
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param userName the value for t_user_info.user_name
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_password
     *
     * @return the value of t_user_info.user_password
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_password
     *
     * @param userPassword the value for t_user_info.user_password
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.mt4_id
     *
     * @return the value of t_user_info.mt4_id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getMt4Id() {
        return mt4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.mt4_id
     *
     * @param mt4Id the value for t_user_info.mt4_id
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setMt4Id(String mt4Id) {
        this.mt4Id = mt4Id == null ? null : mt4Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.mt4_user_group
     *
     * @return the value of t_user_info.mt4_user_group
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getMt4UserGroup() {
        return mt4UserGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.mt4_user_group
     *
     * @param mt4UserGroup the value for t_user_info.mt4_user_group
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setMt4UserGroup(String mt4UserGroup) {
        this.mt4UserGroup = mt4UserGroup == null ? null : mt4UserGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_state
     *
     * @return the value of t_user_info.user_state
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_state
     *
     * @param userState the value for t_user_info.user_state
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_mail
     *
     * @return the value of t_user_info.user_mail
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_mail
     *
     * @param userMail the value for t_user_info.user_mail
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.blance
     *
     * @return the value of t_user_info.blance
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Long getBlance() {
        return blance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.blance
     *
     * @param blance the value for t_user_info.blance
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setBlance(Long blance) {
        this.blance = blance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.certificate_no
     *
     * @return the value of t_user_info.certificate_no
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.certificate_no
     *
     * @param certificateNo the value for t_user_info.certificate_no
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo == null ? null : certificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.certificate_url
     *
     * @return the value of t_user_info.certificate_url
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getCertificateUrl() {
        return certificateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.certificate_url
     *
     * @param certificateUrl the value for t_user_info.certificate_url
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setCertificateUrl(String certificateUrl) {
        this.certificateUrl = certificateUrl == null ? null : certificateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_telphone
     *
     * @return the value of t_user_info.user_telphone
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getUserTelphone() {
        return userTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_telphone
     *
     * @param userTelphone the value for t_user_info.user_telphone
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setUserTelphone(String userTelphone) {
        this.userTelphone = userTelphone == null ? null : userTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_time
     *
     * @return the value of t_user_info.create_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_time
     *
     * @param createTime the value for t_user_info.create_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.last_update_time
     *
     * @return the value of t_user_info.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.last_update_time
     *
     * @param lastUpdateTime the value for t_user_info.last_update_time
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.stat
     *
     * @return the value of t_user_info.stat
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.stat
     *
     * @param stat the value for t_user_info.stat
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}