package com.blackbeard.common.pojo.web;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andMt4IdIsNull() {
            addCriterion("mt4_id is null");
            return (Criteria) this;
        }

        public Criteria andMt4IdIsNotNull() {
            addCriterion("mt4_id is not null");
            return (Criteria) this;
        }

        public Criteria andMt4IdEqualTo(String value) {
            addCriterion("mt4_id =", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdNotEqualTo(String value) {
            addCriterion("mt4_id <>", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdGreaterThan(String value) {
            addCriterion("mt4_id >", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdGreaterThanOrEqualTo(String value) {
            addCriterion("mt4_id >=", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdLessThan(String value) {
            addCriterion("mt4_id <", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdLessThanOrEqualTo(String value) {
            addCriterion("mt4_id <=", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdLike(String value) {
            addCriterion("mt4_id like", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdNotLike(String value) {
            addCriterion("mt4_id not like", value, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdIn(List<String> values) {
            addCriterion("mt4_id in", values, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdNotIn(List<String> values) {
            addCriterion("mt4_id not in", values, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdBetween(String value1, String value2) {
            addCriterion("mt4_id between", value1, value2, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4IdNotBetween(String value1, String value2) {
            addCriterion("mt4_id not between", value1, value2, "mt4Id");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupIsNull() {
            addCriterion("mt4_user_group is null");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupIsNotNull() {
            addCriterion("mt4_user_group is not null");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupEqualTo(String value) {
            addCriterion("mt4_user_group =", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupNotEqualTo(String value) {
            addCriterion("mt4_user_group <>", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupGreaterThan(String value) {
            addCriterion("mt4_user_group >", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupGreaterThanOrEqualTo(String value) {
            addCriterion("mt4_user_group >=", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupLessThan(String value) {
            addCriterion("mt4_user_group <", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupLessThanOrEqualTo(String value) {
            addCriterion("mt4_user_group <=", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupLike(String value) {
            addCriterion("mt4_user_group like", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupNotLike(String value) {
            addCriterion("mt4_user_group not like", value, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupIn(List<String> values) {
            addCriterion("mt4_user_group in", values, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupNotIn(List<String> values) {
            addCriterion("mt4_user_group not in", values, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupBetween(String value1, String value2) {
            addCriterion("mt4_user_group between", value1, value2, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andMt4UserGroupNotBetween(String value1, String value2) {
            addCriterion("mt4_user_group not between", value1, value2, "mt4UserGroup");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("user_state is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("user_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(Integer value) {
            addCriterion("user_state =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(Integer value) {
            addCriterion("user_state <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(Integer value) {
            addCriterion("user_state >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_state >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(Integer value) {
            addCriterion("user_state <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(Integer value) {
            addCriterion("user_state <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<Integer> values) {
            addCriterion("user_state in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<Integer> values) {
            addCriterion("user_state not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(Integer value1, Integer value2) {
            addCriterion("user_state between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(Integer value1, Integer value2) {
            addCriterion("user_state not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserMailIsNull() {
            addCriterion("user_mail is null");
            return (Criteria) this;
        }

        public Criteria andUserMailIsNotNull() {
            addCriterion("user_mail is not null");
            return (Criteria) this;
        }

        public Criteria andUserMailEqualTo(String value) {
            addCriterion("user_mail =", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailNotEqualTo(String value) {
            addCriterion("user_mail <>", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailGreaterThan(String value) {
            addCriterion("user_mail >", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailGreaterThanOrEqualTo(String value) {
            addCriterion("user_mail >=", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailLessThan(String value) {
            addCriterion("user_mail <", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailLessThanOrEqualTo(String value) {
            addCriterion("user_mail <=", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailLike(String value) {
            addCriterion("user_mail like", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailNotLike(String value) {
            addCriterion("user_mail not like", value, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailIn(List<String> values) {
            addCriterion("user_mail in", values, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailNotIn(List<String> values) {
            addCriterion("user_mail not in", values, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailBetween(String value1, String value2) {
            addCriterion("user_mail between", value1, value2, "userMail");
            return (Criteria) this;
        }

        public Criteria andUserMailNotBetween(String value1, String value2) {
            addCriterion("user_mail not between", value1, value2, "userMail");
            return (Criteria) this;
        }

        public Criteria andBlanceIsNull() {
            addCriterion("blance is null");
            return (Criteria) this;
        }

        public Criteria andBlanceIsNotNull() {
            addCriterion("blance is not null");
            return (Criteria) this;
        }

        public Criteria andBlanceEqualTo(Long value) {
            addCriterion("blance =", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceNotEqualTo(Long value) {
            addCriterion("blance <>", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceGreaterThan(Long value) {
            addCriterion("blance >", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceGreaterThanOrEqualTo(Long value) {
            addCriterion("blance >=", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceLessThan(Long value) {
            addCriterion("blance <", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceLessThanOrEqualTo(Long value) {
            addCriterion("blance <=", value, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceIn(List<Long> values) {
            addCriterion("blance in", values, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceNotIn(List<Long> values) {
            addCriterion("blance not in", values, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceBetween(Long value1, Long value2) {
            addCriterion("blance between", value1, value2, "blance");
            return (Criteria) this;
        }

        public Criteria andBlanceNotBetween(Long value1, Long value2) {
            addCriterion("blance not between", value1, value2, "blance");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIsNull() {
            addCriterion("certificate_no is null");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIsNotNull() {
            addCriterion("certificate_no is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateNoEqualTo(String value) {
            addCriterion("certificate_no =", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotEqualTo(String value) {
            addCriterion("certificate_no <>", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoGreaterThan(String value) {
            addCriterion("certificate_no >", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoGreaterThanOrEqualTo(String value) {
            addCriterion("certificate_no >=", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLessThan(String value) {
            addCriterion("certificate_no <", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLessThanOrEqualTo(String value) {
            addCriterion("certificate_no <=", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLike(String value) {
            addCriterion("certificate_no like", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotLike(String value) {
            addCriterion("certificate_no not like", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIn(List<String> values) {
            addCriterion("certificate_no in", values, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotIn(List<String> values) {
            addCriterion("certificate_no not in", values, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoBetween(String value1, String value2) {
            addCriterion("certificate_no between", value1, value2, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotBetween(String value1, String value2) {
            addCriterion("certificate_no not between", value1, value2, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlIsNull() {
            addCriterion("certificate_url is null");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlIsNotNull() {
            addCriterion("certificate_url is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlEqualTo(String value) {
            addCriterion("certificate_url =", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlNotEqualTo(String value) {
            addCriterion("certificate_url <>", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlGreaterThan(String value) {
            addCriterion("certificate_url >", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlGreaterThanOrEqualTo(String value) {
            addCriterion("certificate_url >=", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlLessThan(String value) {
            addCriterion("certificate_url <", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlLessThanOrEqualTo(String value) {
            addCriterion("certificate_url <=", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlLike(String value) {
            addCriterion("certificate_url like", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlNotLike(String value) {
            addCriterion("certificate_url not like", value, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlIn(List<String> values) {
            addCriterion("certificate_url in", values, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlNotIn(List<String> values) {
            addCriterion("certificate_url not in", values, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlBetween(String value1, String value2) {
            addCriterion("certificate_url between", value1, value2, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andCertificateUrlNotBetween(String value1, String value2) {
            addCriterion("certificate_url not between", value1, value2, "certificateUrl");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIsNull() {
            addCriterion("user_telphone is null");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIsNotNull() {
            addCriterion("user_telphone is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneEqualTo(String value) {
            addCriterion("user_telphone =", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotEqualTo(String value) {
            addCriterion("user_telphone <>", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneGreaterThan(String value) {
            addCriterion("user_telphone >", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_telphone >=", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLessThan(String value) {
            addCriterion("user_telphone <", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLessThanOrEqualTo(String value) {
            addCriterion("user_telphone <=", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLike(String value) {
            addCriterion("user_telphone like", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotLike(String value) {
            addCriterion("user_telphone not like", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIn(List<String> values) {
            addCriterion("user_telphone in", values, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotIn(List<String> values) {
            addCriterion("user_telphone not in", values, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneBetween(String value1, String value2) {
            addCriterion("user_telphone between", value1, value2, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotBetween(String value1, String value2) {
            addCriterion("user_telphone not between", value1, value2, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 29 15:32:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Jun 29 15:32:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}