package com.blackbeard.common.pojo.web;

import java.util.Date;

public class UserRechangeFailureRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.mt4_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private String mt4Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.user_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.recharge_money
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private Long rechargeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.create_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.last_update_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_recharge_failure_record.stat
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.id
     *
     * @return the value of t_user_recharge_failure_record.id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.id
     *
     * @param id the value for t_user_recharge_failure_record.id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.mt4_id
     *
     * @return the value of t_user_recharge_failure_record.mt4_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public String getMt4Id() {
        return mt4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.mt4_id
     *
     * @param mt4Id the value for t_user_recharge_failure_record.mt4_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setMt4Id(String mt4Id) {
        this.mt4Id = mt4Id == null ? null : mt4Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.user_id
     *
     * @return the value of t_user_recharge_failure_record.user_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.user_id
     *
     * @param userId the value for t_user_recharge_failure_record.user_id
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.recharge_money
     *
     * @return the value of t_user_recharge_failure_record.recharge_money
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public Long getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.recharge_money
     *
     * @param rechargeMoney the value for t_user_recharge_failure_record.recharge_money
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setRechargeMoney(Long rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.create_time
     *
     * @return the value of t_user_recharge_failure_record.create_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.create_time
     *
     * @param createTime the value for t_user_recharge_failure_record.create_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.last_update_time
     *
     * @return the value of t_user_recharge_failure_record.last_update_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.last_update_time
     *
     * @param lastUpdateTime the value for t_user_recharge_failure_record.last_update_time
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_recharge_failure_record.stat
     *
     * @return the value of t_user_recharge_failure_record.stat
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_recharge_failure_record.stat
     *
     * @param stat the value for t_user_recharge_failure_record.stat
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}