package com.blackbeard.common.mapper.web;

import com.blackbeard.common.pojo.web.AccountConfig;
import com.blackbeard.common.pojo.web.AccountConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int countByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int deleteByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int insert(AccountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int insertSelective(AccountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    List<AccountConfig> selectByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    AccountConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int updateByExample(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int updateByPrimaryKeySelective(AccountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_config
     *
     * @mbggenerated Wed Jul 20 10:12:32 CST 2016
     */
    int updateByPrimaryKey(AccountConfig record);
}