package com.blackbeard.common.mapper.web;

import com.blackbeard.common.pojo.web.CurrencyConfig;
import com.blackbeard.common.pojo.web.CurrencyConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurrencyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int countByExample(CurrencyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int deleteByExample(CurrencyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int insert(CurrencyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int insertSelective(CurrencyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    List<CurrencyConfig> selectByExample(CurrencyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    CurrencyConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") CurrencyConfig record, @Param("example") CurrencyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int updateByExample(@Param("record") CurrencyConfig record, @Param("example") CurrencyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int updateByPrimaryKeySelective(CurrencyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency_config
     *
     * @mbggenerated Tue Aug 02 11:19:41 CST 2016
     */
    int updateByPrimaryKey(CurrencyConfig record);
}