package com.blackbeard.common.mapper.web;

import com.blackbeard.common.pojo.web.Mt4Config;
import com.blackbeard.common.pojo.web.Mt4ConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Mt4ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int countByExample(Mt4ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int deleteByExample(Mt4ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int insert(Mt4Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int insertSelective(Mt4Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    List<Mt4Config> selectByExample(Mt4ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    Mt4Config selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") Mt4Config record, @Param("example") Mt4ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int updateByExample(@Param("record") Mt4Config record, @Param("example") Mt4ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int updateByPrimaryKeySelective(Mt4Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mt4_config
     *
     * @mbggenerated Wed Jun 29 15:39:13 CST 2016
     */
    int updateByPrimaryKey(Mt4Config record);
}