package com.blackbeard.common.mapper.web;

import com.blackbeard.common.pojo.web.UserRechangeFailureRecord;
import com.blackbeard.common.pojo.web.UserRechangeFailureRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRechangeFailureRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int countByExample(UserRechangeFailureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int deleteByExample(UserRechangeFailureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int insert(UserRechangeFailureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int insertSelective(UserRechangeFailureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    List<UserRechangeFailureRecord> selectByExample(UserRechangeFailureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    UserRechangeFailureRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserRechangeFailureRecord record, @Param("example") UserRechangeFailureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int updateByExample(@Param("record") UserRechangeFailureRecord record, @Param("example") UserRechangeFailureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int updateByPrimaryKeySelective(UserRechangeFailureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_recharge_failure_record
     *
     * @mbggenerated Thu Jul 14 09:11:25 CST 2016
     */
    int updateByPrimaryKey(UserRechangeFailureRecord record);
}