package com.blackbeard.common.mapper.order;

import com.blackbeard.common.pojo.order.HistoryOrder;
import com.blackbeard.common.pojo.order.HistoryOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int countByExample(HistoryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int deleteByExample(HistoryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int insert(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int insertSelective(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    List<HistoryOrder> selectByExample(HistoryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    HistoryOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") HistoryOrder record, @Param("example") HistoryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int updateByExample(@Param("record") HistoryOrder record, @Param("example") HistoryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int updateByPrimaryKeySelective(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_order
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    int updateByPrimaryKey(HistoryOrder record);
}