package com.blackbeard.common.pojo.order;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

public class HistoryOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.close_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.close_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.cmd
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Integer cmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.comment
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.login_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Long loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.user_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.open_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.open_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.profit
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Float profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.symbol
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.total
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.tick
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Long tick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.stat
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.create_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_order.update_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    private Date updateTime;
    
    @Getter
	@Setter
	private String openTimeStart; // 开盘价开始查询时间
	@Getter
	@Setter
	private String openTimeEnd; // 开盘价结束查询时间

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.id
     *
     * @return the value of t_history_order.id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.id
     *
     * @param id the value for t_history_order.id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.close_price
     *
     * @return the value of t_history_order.close_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.close_price
     *
     * @param closePrice the value for t_history_order.close_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setClosePrice(String closePrice) {
        this.closePrice = closePrice == null ? null : closePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.close_time
     *
     * @return the value of t_history_order.close_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.close_time
     *
     * @param closeTime the value for t_history_order.close_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setCloseTime(String closeTime) {
        this.closeTime = closeTime == null ? null : closeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.cmd
     *
     * @return the value of t_history_order.cmd
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Integer getCmd() {
        return cmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.cmd
     *
     * @param cmd the value for t_history_order.cmd
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setCmd(Integer cmd) {
        this.cmd = cmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.comment
     *
     * @return the value of t_history_order.comment
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.comment
     *
     * @param comment the value for t_history_order.comment
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.login_id
     *
     * @return the value of t_history_order.login_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Long getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.login_id
     *
     * @param loginId the value for t_history_order.login_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.user_id
     *
     * @return the value of t_history_order.user_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.user_id
     *
     * @param userId the value for t_history_order.user_id
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.open_price
     *
     * @return the value of t_history_order.open_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.open_price
     *
     * @param openPrice the value for t_history_order.open_price
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setOpenPrice(String openPrice) {
        this.openPrice = openPrice == null ? null : openPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.open_time
     *
     * @return the value of t_history_order.open_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.open_time
     *
     * @param openTime the value for t_history_order.open_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.profit
     *
     * @return the value of t_history_order.profit
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Float getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.profit
     *
     * @param profit the value for t_history_order.profit
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setProfit(Float profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.symbol
     *
     * @return the value of t_history_order.symbol
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.symbol
     *
     * @param symbol the value for t_history_order.symbol
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.total
     *
     * @return the value of t_history_order.total
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.total
     *
     * @param total the value for t_history_order.total
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.tick
     *
     * @return the value of t_history_order.tick
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Long getTick() {
        return tick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.tick
     *
     * @param tick the value for t_history_order.tick
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setTick(Long tick) {
        this.tick = tick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.stat
     *
     * @return the value of t_history_order.stat
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.stat
     *
     * @param stat the value for t_history_order.stat
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.create_time
     *
     * @return the value of t_history_order.create_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.create_time
     *
     * @param createTime the value for t_history_order.create_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_order.update_time
     *
     * @return the value of t_history_order.update_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_order.update_time
     *
     * @param updateTime the value for t_history_order.update_time
     *
     * @mbggenerated Tue Jul 19 16:38:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}